<?php
namespace app\common\model;

class ActJoin extends BaseModel
{

    protected $name='act_join';
    public static $fields_sex=['','男','女'];

    //
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub




        self::event('after_insert',function($model){
            //增加养分
            $setting_content = SysSetting::getContent('normal');
            $setting_content = json_decode($setting_content,true);

            $num = isset($setting_content['activity_raise_num'])?explode(',',$setting_content['activity_raise_num']):[];
            $award_num = empty($num[0])?10:$num[0];
            $award_limit = isset($num[1])?$num[1]:1;
            //获取用户奖励次数
            $award_times = UsersRaiseLogs::where([['uid','=',$model['uid']],['type','=',7],['create_time','>=',date('Y-m-d').' 00:00:00']])->count();
            if(empty($award_limit) || empty($award_times) || $award_times<$award_limit){
                //增加养分
                $user_model = Users::get($model['uid']);
                if($num>0 && !empty($user_model)){
                    $user_model->recordRaise($award_num,7,'参加活动获得:'.$award_num.'养分');
                }
            }

        });
    }

}