<?php
namespace app\common\model;

class ActJoin extends BaseModel
{

    protected $name='act_join';


    //
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        self::event('after_insert',function($model){
            //增加养分
            $setting_content = SysSetting::getContent('normal');
            $setting_content = json_decode($setting_content,true);
            $num = isset($setting_content['activity_raise_num'])?$setting_content['activity_raise_num']:0;
            $user_model = Users::get($model['uid']);
            if($num>0 && !empty($user_model)){
                $user_model->recordRaise($num,7,'参加活动获得:'.$num.'养分');
            }
        });
    }
}