<?php
namespace app\common\model;

class UsersHealth extends BaseModel
{

    protected $name='users_health';
    /**
     * @var Users
     * */
    protected $user_model;
    public static $fields_type = [
        ['name'=>'步数'],
        ['name'=>'体重'],
        ['name'=>'视力','is_only'=>true], //单条记录
        ['name'=>'血压'],
        ['name'=>'血糖'],
        ['name'=>'血脂'],
        ['name'=>'心率'],
    ];

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        self::event('after_insert',function($model){
            //新增数据获得养分
             if(!empty($model->user_model)){
                 //增加邀请人数
                 $setting_content = SysSetting::getContent('normal');
                 $setting_content = json_decode($setting_content,true);
                 $num = isset($setting_content['healthy_raise_num'])?$setting_content['healthy_raise_num']:0;
                 $num>0 && $model->user_model->recordRaise($num, 8,'更新健康信息获得:'.$num.'养分');
             }
        });
    }

    /**
     * 记录健康数据
     * @param $user_model Users 用户模型
     * @param $num int|string 健康数据
     * @param $type int 数据类型
     * @throws
     * @return self
     * */
    public static function setHealthData(Users $user_model,$num,$type=0)
    {
        $type_info = self::getPropInfo('fields_type',$type);
        empty($type_info) && exception('更新信息异常:type');

        $day = date('Y-m-d');
        $model = self::where(['uid'=>$user_model->id,'type'=>$type])->order('date desc')->find();
        if(empty($model)){
            $model = new self();
        }elseif($model['date']!==$day){
            if(!isset($type_info['is_only'])){
                $model = new self();
            }
        }else{

        }
        $model->user_model = $user_model;
        $model->setAttr('type',$type);
        $model->uid = $user_model->id;
        $model->num = $num;
        $model->date = $day;
        $model->save();
        return $model;
    }

}