<?php
namespace app\common\model;


use think\model\concern\SoftDelete;

class Video extends BaseModel
{
    use SoftDelete;
    public static $fields_status = ['待审核','正常','关闭'];

    protected $name='video';

    protected $insert = ['uid'];

    protected function setUidAttr($value,$data)
    {
        return empty($value)?1:(int)$value;
    }

    //状态
//    public function setStatusAttr($value)
//    {
//        return empty($value)?0:$value;
//    }

    //发布时间
    protected function getReleaseDateAttr()
    {
        return $this->create_time;
    }
    //设置视频有效时间
    protected function setDurationAttr($value)
    {
        return empty($value)?'00:00:00':sprintf('%02d:%02d:%02d',substr(intval($value/60/60*100),0,-2),intval($value/60%60),intval($value%60));
    }

    protected function setTitleAttr($value)
    {
        return empty($value)?'':strip_tags($value);
    }

    //定位信息
    protected function setLocationPoiAttr($value)
    {
        if(!empty($value)){
//            exception($value);
            $poi = json_decode($value,true);

            $this->setAttr('coordinate',(isset($poi['lng']) && isset($poi['lat'])) ? ($poi['lng'].','. $poi['lat'] ):'');
            $this->setAttr('addr',isset($poi['address'])?$poi['address']:'');
        }
        return $value;
    }

    //发布的文件组合
    protected function getFileGroupAttr()
    {
        $data=[
            'type'=>'video',
            'data'=>[
                [
                    'file' => self::handleFile($this->file),
                    'img' => self::handleFile($this->getData('img')),
                ]
            ]
        ];
        return $data;
    }


    public function getStatusIntroAttr()
    {
        if(empty($this->is_auth)){
            return '待审核';
        }elseif($this->is_auth==2){
            return '已被拒';
        }else{
            return self::getPropInfo('fields_status',$this->status);
        }
    }

    public function getStatusClassAttr()
    {
        if(empty($this->is_auth)){
            return 'wait';
        }elseif($this->is_auth==2){
            return 'warring';
        }else{
            return 'normal';
        }
    }


    //
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //审核通过
        self::event('auth_success',function($model){
            //增加养分
            $setting_content = SysSetting::getContent('normal');
            $setting_content = json_decode($setting_content,true);
            $num = isset($setting_content['video_raise_num'])?explode(',',$setting_content['video_raise_num']):[];
            $award_num = empty($num[0])?5:$num[0];
            $award_limit = isset($num[1])?$num[1]:3;
            //获取用户奖励次数
            $award_times = UsersRaiseLogs::where([['uid','=',$model['uid']],['type','=',6],['create_time','>=',date('Y-m-d').' 00:00:00']])->count();
            if(empty($award_limit) || empty($award_times) || $award_times<$award_limit){
                //
                $user_model = Users::get($model['uid']);
                if($num>0 && !empty($user_model)){
                    $user_model->recordRaise($award_num,6,'发布视频获得:'.$award_num.'养分');
                }
            }
        });

        self::event('after_insert',function($model){


        });
    }


    //视频封面图
    protected function setImgAttr($value,$data)
    {
        if($value){
            return $value;
        }
        $file = isset($data['file'])?$data['file']:'';
        return empty($file)?'/uploads/video_cover/default.jpg':$file.'.jpg';
    }


    protected function getImgAttr($value)
    {
        return self::handleFile($value);
    }

    protected function getFileAttr($value)
    {
        return self::handleFile($value);
    }

    protected function getLabelsAttr($value)
    {
        return empty($value)?[]:explode(',',$value);
    }

    /**
     * 评论
     * @param Users $user_model;
     * @param array $data;
     * @throws
     * @return DyPraise
     * */
    public static function praise(Users $user_model,array $data=[])
    {
        empty($data['id']) && exception('对象异常:id');
        $ex_model = self::get($data['id']);
        empty($ex_model) && exception('对象异常:null');

        $model = VideoPraise::where(['uid'=>$user_model->id,'vid'=>$data['id']])->find();
        if(empty($model)){
            $model = new VideoPraise();
        }

        $model->uid = $user_model->id;
        $model->vid = $data['id'];
        $model->praise_date = empty($model->praise_date)?date('Y-m-d H:i:s'):null;
        $model->save();
        //点赞次数增加
        $model->praise_date?$ex_model->setInc('praise_times'):$ex_model->setDec('praise_times');

        //增加用户点赞次数
        try{
            //被点用户
            $opt_user_model = Users::get($ex_model['uid']);
            $model->praise_date?$opt_user_model->setInc('praise_num'):$opt_user_model->setDec('praise_num');
            //触发点赞奖励事件
            if(!empty($opt_user_model)  && empty($opt_user_model->praise_num%Users::PRAISE_TIMES_AWARD)){
                $opt_user_model->trigger('praise_award');
            }

        }catch (\Exception $e){
        }

        return $model;
    }


    /**
     * 评论
     * @param Users $user_model;
     * @param array $data;
     * @throws
     * @return VideoComment
     * */
    public static function addComment(Users $user_model,array $data=[])
    {
        empty($data['content']) && exception('内容不能为空');
        empty($data['id']) && exception('对象异常:id');

        $model = new VideoComment();
        $model->uid = $user_model->id;
        $model->vid = $data['id'];
        $model->to_uid = empty($data['to_uid'])?0:$data['to_uid'];
        $model->pid = empty($data['pid'])?0:$data['pid'];
        $model->content = $data['content'];
        $model->save();
        return $model;
    }


    /**
     * 删除
     * @param Users $user_model|null;
     * @param array $data;
     * @throws
     * */
    public static function Del(Users $user_model=null,array $data=[])
    {
        empty($data['id']) && exception('对象异常:id');
        $model = self::get($data['id']);
        empty($model) && exception('已被删除');
        if(!empty($user_model) && $user_model['id']!=$model['uid']){
            exception('无法进行此操作');
        }
        //直接删除
        $model->delete();
    }


    //动态用户
    public function linkUsers()
    {
        return $this->belongsTo('Users','uid');
    }

    //动态评论
    public function linkCommentCount()
    {
        return $this->hasOne('VideoComment','vid')->field('vid,count(*) as comment_count')->group('vid');
    }

    //是否点过赞
    public function linkIsPraise()
    {
        return $this->hasOne('VideoPraise','vid')->whereNotNull('praise_date');
    }
}