<?php
namespace app\index\controller;

class Upload extends Common
{
    private $root_path;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->root_path = \think\facade\Env::get('root_path');
    }

    public function upload($type='images',$open_info=0)
    {
        $upload_file_key=key($_FILES);
        // 获取表单上传文件 例如上传了001.jpg
        $file = request()->file($upload_file_key);
        //上传路径
        $save_path = '/uploads/'.$type.'/';
        // 移动到框架应用根目录/uploads/ 目录下
        $info = $file->move( $this->root_path.$save_path);
        if($info){
            // 成功上传后 获取上传信息
            $data = [
                'path'=>str_replace('\\','/',$save_path.$info->getSaveName()),
            ];
            if($open_info){
                $data['size'] = round($info->getSize()/1024);
                $data['type'] = $info->getExtension();
            }
            echo  json_encode(array_merge([ 'code'=>1,'msg'=>'上传成功'],$data));
        }else{
            // 上传失败获取错误信息
            echo  json_encode([ 'code'=>0,'msg'=>$file->getError()]);
        }

    }

    public function delimg(){
        $imgpath = $this->request->param('imgpath');
        unlink($this->root_path.$imgpath);
        echo 1;
    }
}
